import type { Product } from "@src/shared";

export const products_mock: Product[] = [
  {
    id: 1,
    name: "Ceramic Coffee Mug",
    description: "A stylish ceramic coffee mug perfect for your morning coffee.",
    price: 29.99,
    imageUrl: "https://plus.unsplash.com/premium_photo-1667621221177-a10b4fb30b08?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "mug",
    stock: 100,
    colors: ["white", "black", "blue"],
    discount: 10,
    big_description: "Elevate your morning coffee experience with our beautifully designed Ceramic Coffee Mug. Crafted from high-quality ceramic, this mug combines durability with a sleek, modern aesthetic, making it a perfect addition to any kitchen or office setting. \n With its comfortable grip and generous capacity, this stylish mug is designed for everyday use, whether you’re enjoying a hot cup of coffee, tea, or your favorite beverage. The smooth, glossy finish adds a touch of elegance, while the vibrant colors and unique patterns make it a statement piece that reflects your personality. \n This mug is not just functional; it's also dishwasher and microwave safe, ensuring convenience and easy maintenance for your busy lifestyle. Ideal for personal use or as a thoughtful gift for friends and family, this Ceramic Coffee Mug is sure to brighten anyone’s day. Treat yourself or a loved one to this perfect blend of style and functionality!",
  },
  {
    id: 2,
    name: "Travel Mug",
    description: "A stainless steel travel mug with a spill-proof lid.",
    price: 4.99,
    imageUrl: "https://images.unsplash.com/photo-1588793076577-4c2b666452d3?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "mug",
    stock: 0,
    colors: ["silver", "red", "green"],
    discount: 0,
    big_description: "Stay refreshed and stylish with our premium Travel Mug, expertly designed for those who are always on the move. Made from high-quality stainless steel, this travel mug ensures durability and resistance to rust and corrosion, making it perfect for daily use, whether you're commuting to work, hitting the gym, or embarking on an adventure. \n The spill-proof lid features a secure locking mechanism, allowing you to enjoy your favorite beverages without worrying about leaks or spills. Designed for one-handed operation, this mug is ideal for multitasking, whether you’re navigating a busy street or working at your desk. \n With an insulated interior, it keeps your drinks hot or cold for hours, ensuring that your coffee stays piping hot during your morning commute, while your iced tea remains refreshingly cool throughout the day. The sleek, modern design fits most cup holders, making it easy to take with you wherever you go. \n Available in a range of stylish colors, this travel mug not only offers practicality but also allows you to express your personal style. Perfect for busy professionals, students, or anyone who loves their beverages on the go, the Travel Mug is a must-have accessory for a dynamic lifestyle. Treat yourself or surprise a loved one with this perfect blend of convenience and elegance!",
  },
  {
    id: 3,
    name: "Personalized Mug",
    description: "A customizable mug with your name or a special message.",
    price: 12.99,
    imageUrl: "https://images.unsplash.com/photo-1620767188495-98ce5155895e?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "mug",
    stock: 10,
    colors: ["white", "yellow", "pink"],
    discount: 40,
    big_description: "This customizable ceramic mug is the ideal way to enjoy your favorite hot beverage while adding a personal touch. Featuring high-quality, durable materials, it is built to withstand daily use and repeated washing. The mug can be customized with your name, a special message, or any unique design, making it a perfect gift for birthdays, anniversaries, holidays, or even as a treat for yourself. \n Choose from various fonts, colors, and design styles to create a truly one-of-a-kind item. The glossy finish gives the mug a sleek, professional look that will complement any kitchen or office decor. Whether you're sipping coffee, tea, or hot chocolate, this personalized mug will bring a smile to your face every time you use it. \n It’s not just a drinkware item; it’s a keepsake that holds sentimental value. With its classic 11 oz size, it's perfect for everyday use and microwave and dishwasher safe for convenience. Order one for yourself or surprise your loved ones with a personalized gift they’ll cherish.",
  },
  {
    id: 4,
    name: "Graphic Tee",
    description: "A trendy graphic t-shirt for casual outings.",
    price: 9.99,
    imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1528&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "t-shirt",
    stock: 75,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "navy", "grey"],
    discount: 50,
    big_description: "Step out in style with our trendy Graphic Tee, designed to elevate your casual wardrobe. Made from soft, breathable fabric, this t-shirt offers all-day comfort while making a bold fashion statement. The eye-catching graphics showcase unique designs that reflect your personality, whether you're into vintage vibes, modern art, or playful slogans.\n  Perfect for pairing with jeans, shorts, or skirts, this versatile tee is an essential piece for any casual outing, from weekend brunches to hanging out with friends. Its relaxed fit flatters all body types, ensuring you look and feel great no matter where the day takes you. \n Available in a variety of sizes and colors, our Graphic Tee allows you to express your individuality while staying comfortable. With its durable construction and easy-care fabric, this t-shirt is built to last, making it a staple in your everyday wardrobe. \n Upgrade your casual style with our Graphic Tee – the perfect blend of comfort, quality, and trendiness that will keep you looking effortlessly chic!",
  },
  {
    id: 5,
    name: "Plain Cotton T-Shirt",
    description: "A comfortable plain cotton t-shirt, ideal for everyday wear.",
    price: 15.99,
    imageUrl: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "t-shirt",
    stock: 8.99,
    sizes: ["M", "L", "XL"],
    colors: ["white", "blue", "red"],
    discount: 0,
    big_description: "Discover the perfect blend of comfort and style with our Plain Cotton T-Shirt, designed to be your go-to choice for everyday wear. Crafted from 100% high-quality cotton, this t-shirt is incredibly soft against the skin, providing breathability and ease that makes it perfect for any occasion. \n With its classic fit and timeless design, this t-shirt is versatile enough to pair with jeans, shorts, or even layered under a jacket for a more polished look. Whether you’re running errands, lounging at home, or meeting friends for coffee, this Plain Cotton T-Shirt ensures you feel comfortable and confident all day long. \n Available in a range of sizes and colors, it’s easy to find the perfect fit for your wardrobe. The durable fabric withstands frequent washing while retaining its shape and color, making it a lasting staple in your closet. \n Elevate your casual style with this essential Plain Cotton T-Shirt—a wardrobe must-have that combines simplicity, quality, and comfort in one package!",
  },
  {
    id: 6,
    name: "Vintage T-Shirt",
    description: "A vintage style t-shirt with a retro logo.",
    price: 21.99,
    imageUrl: "https://images.unsplash.com/photo-1609123100658-04923eef862e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHZpbnRhZ2UlMjBjbG90aGluZ3xlbnwwfHwwfHx8MA%3D%3D",
    category: "t-shirt",
    stock: 0,
    sizes: ["S", "M", "L"],
    colors: ["green", "black", "white"],
    discount: 15,
    big_description: "Step back in time with our Vintage T-Shirt, a perfect blend of classic design and contemporary comfort. Featuring a retro logo that captures the essence of nostalgic fashion, this t-shirt is an ideal choice for those who appreciate the charm of vintage aesthetics. \n Crafted from soft, high-quality cotton, this t-shirt ensures a comfortable fit that feels great against the skin. The relaxed silhouette offers ease of movement, making it perfect for casual outings, weekend adventures, or simply lounging at home. \n Whether you’re pairing it with distressed jeans, shorts, or a denim jacket, this Vintage T-Shirt effortlessly elevates any outfit. The unique, eye-catching design adds character to your wardrobe, allowing you to express your individuality and love for retro fashion. \n Available in a variety of sizes, this t-shirt is designed to suit everyone. The durable fabric is not only comfortable but also built to last, maintaining its shape and vibrancy through countless washes. Add a touch of nostalgia to your everyday look with our Vintage T-Shirt—the ultimate choice for anyone looking to blend style and comfort in a timeless piece!",
  },
  {
    id: 7,
    name: "Lined Notebook",
    description: "A classic lined notebook for all your notes and ideas.",
    price: 4.99,
    imageUrl: "https://plus.unsplash.com/premium_photo-1667251760532-85310936c89a?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "notebook",
    stock: 200,
    sizes: ["A5", "A4"],
    colors: ["black", "blue", "red"],
    discount: 0,
    big_description: "Unleash your creativity and keep your thoughts organized with our Lined Notebook, designed for those who appreciate the beauty of simplicity and functionality. This classic notebook features high-quality lined pages, making it perfect for jotting down notes, brainstorming ideas, or keeping a journal. \n With its durable cover and sturdy binding, this notebook is built to withstand daily use, whether you're in a lecture, meeting, or simply working from home. The smooth, acid-free paper provides a luxurious writing experience, preventing ink bleed-through and ensuring that your notes remain clear and legible. \n Available in various sizes and styles, the Lined Notebook is versatile enough to fit any occasion—carry it in your bag, keep it on your desk, or use it for creative writing, sketching, or planning. The minimalist design adds a touch of elegance, making it suitable for students, professionals, and anyone who values quality stationery. \n Elevate your note-taking game with our Lined Notebook—the perfect tool for capturing thoughts, ideas, and inspiration in a timeless format!",
  },
  {
    id: 8,
    name: "Sketchbook",
    description: "A sketchbook with blank pages for artists and doodlers.",
    price: 8.99,
    imageUrl: "https://plus.unsplash.com/premium_photo-1683309565307-fc8dc2dc18c0?q=80&w=1587&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "notebook",
    stock: 150,
    sizes: ["A5", "A4"],
    colors: ["white", "brown"],
    discount: 80,
    big_description: "Ignite your creativity with our premium Sketchbook, designed for artists, doodlers, and anyone who loves to express themselves through drawing. Featuring blank pages that invite limitless possibilities, this sketchbook is the perfect companion for capturing your thoughts, ideas, and inspirations. \n Crafted with high-quality, acid-free paper, it ensures smooth and effortless sketching, whether you're using pencils, pens, markers, or charcoal. The thick pages prevent bleed-through, allowing you to explore various mediums without worry, making it ideal for both detailed illustrations and spontaneous doodles. \n With its durable cover and sturdy binding, the Sketchbook is built to withstand the rigors of travel and everyday use. Whether you’re sketching in the park, taking notes in class, or creating your next masterpiece at home, this sketchbook is versatile enough to accompany you anywhere. \n Available in different sizes, it’s perfect for every creative endeavor—from small pocket-sized sketches to larger works of art. Embrace your artistic side and bring your ideas to life with our Sketchbook, where every page is a blank canvas waiting for your unique touch!",
  },
  {
    id: 9,
    name: "Bullet Journal",
    description: "A bullet journal for planning and organizing your tasks.",
    price: 6.99,
    imageUrl: "https://plus.unsplash.com/premium_photo-1663852904478-46298efac74b?q=80&w=1676&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "notebook",
    stock: 120,
    sizes: ["A5", "A4"],
    colors: ["black", "grey"],
    discount: 0,
    big_description: "Take control of your life and boost your productivity with our Bullet Journal, designed for those who want to effectively plan and organize their tasks. This versatile journal combines the simplicity of traditional note-taking with the flexibility of modern organization, making it the perfect companion for students, professionals, and anyone looking to enhance their daily routines. \n Featuring dotted pages, this Bullet Journal allows you to customize layouts that suit your unique style—whether it's daily logs, monthly spreads, habit trackers, or creative doodles. The high-quality, acid-free paper ensures a smooth writing experience, preventing ink bleed-through and allowing you to use your favorite pens and markers with confidence. \n With its durable cover and sturdy binding, this journal is built to withstand daily use, making it easy to carry along wherever you go. Available in various sizes and colors, it’s designed to fit seamlessly into your lifestyle, whether you prefer a compact notebook for on-the-go planning or a larger journal for expansive layouts. \n Embrace the art of organization and transform your planning habits with our Bullet Journal—a creative space where you can bring order to your thoughts and tasks, allowing you to focus on what truly matters!",
  },
];
